# Generated by Django 5.2.3 on 2025-07-31 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('policy_type', models.CharField(choices=[('crop', 'Crop'), ('livestock', 'Livestock'), ('flood', 'Flood'), ('fire', 'Fire'), ('other', 'Other')], max_length=20)),
                ('premium', models.DecimalField(decimal_places=2, max_digits=10)),
                ('coverage', models.TextField(help_text='Describe what the policy covers')),
                ('duration_months', models.PositiveIntegerField(default=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
