# Generated by Django 5.2.3 on 2025-07-31 11:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policy',
            options={'ordering': ['policy_type', 'name'], 'verbose_name_plural': 'Policies'},
        ),
        migrations.RemoveField(
            model_name='policy',
            name='premium',
        ),
        migrations.AddField(
            model_name='policy',
            name='base_premium',
            field=models.DecimalField(decimal_places=2, default=1000, help_text='Base premium amount in KSh', max_digits=10),
        ),
        migrations.AddField(
            model_name='policy',
            name='description',
            field=models.TextField(default='', help_text='Detailed description of the policy'),
        ),
        migrations.AddField(
            model_name='policy',
            name='eligibility_criteria',
            field=models.JSONField(default=dict, help_text='Eligibility requirements'),
        ),
        migrations.AddField(
            model_name='policy',
            name='exclusions',
            field=models.TextField(blank=True, help_text='What is not covered'),
        ),
        migrations.AddField(
            model_name='policy',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='max_sum_insured',
            field=models.DecimalField(decimal_places=2, default=10000000, max_digits=12),
        ),
        migrations.AddField(
            model_name='policy',
            name='min_sum_insured',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=12),
        ),
        migrations.AddField(
            model_name='policy',
            name='premium_rate',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Premium rate as percentage of sum insured', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='policy',
            name='required_documents',
            field=models.JSONField(default=list, help_text='List of required documents'),
        ),
        migrations.AddField(
            model_name='policy',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='waiting_period_days',
            field=models.PositiveIntegerField(default=14, help_text='Days before coverage starts'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='coverage',
            field=models.TextField(help_text='What the policy covers'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='policy_type',
            field=models.CharField(choices=[('crop', 'Crop Insurance'), ('livestock', 'Livestock Insurance'), ('weather_index', 'Weather Index Insurance'), ('equipment', 'Farm Equipment Insurance'), ('greenhouse', 'Greenhouse Insurance'), ('poultry', 'Poultry Insurance'), ('aquaculture', 'Aquaculture Insurance'), ('storage', 'Post-Harvest Storage Insurance')], max_length=20),
        ),
        migrations.AlterModelTable(
            name='policy',
            table='policies',
        ),
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('claim_type', models.CharField(choices=[('crop_loss', 'Crop Loss'), ('livestock_death', 'Livestock Death'), ('weather_damage', 'Weather Damage'), ('disease', 'Disease/Pest Damage'), ('theft', 'Theft'), ('fire', 'Fire Damage'), ('flood', 'Flood Damage'), ('equipment_damage', 'Equipment Damage'), ('other', 'Other')], max_length=20)),
                ('incident_date', models.DateField()),
                ('description', models.TextField()),
                ('loss_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('assessed_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('assessment_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('site_inspection', 'Site Inspection Scheduled'), ('processing', 'Processing'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid'), ('closed', 'Closed')], default='submitted', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_claims', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'claims',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('sum_insured', models.DecimalField(decimal_places=2, max_digits=12)),
                ('premium_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insured_area_acres', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('insured_crop', models.CharField(blank=True, max_length=100)),
                ('insured_livestock_count', models.PositiveIntegerField(blank=True, null=True)),
                ('asset_details', models.JSONField(blank=True, default=dict)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='core.policy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subscriptions',
                'ordering': ['-subscribed_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('payment_type', models.CharField(choices=[('premium', 'Premium Payment'), ('claim', 'Claim Settlement'), ('refund', 'Refund')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('mpesa', 'M-Pesa'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('cheque', 'Cheque')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('gateway_ref', models.CharField(blank=True, help_text='Payment gateway reference', max_length=100)),
                ('phone_number', models.CharField(blank=True, help_text='Phone number used for payment', max_length=15)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.claim')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.subscription')),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('id_card', 'National ID Card'), ('farm_photo', 'Farm Photo'), ('ownership_doc', 'Land Ownership Document'), ('loss_evidence', 'Loss Evidence'), ('assessment_report', 'Assessment Report'), ('receipt', 'Receipt'), ('other', 'Other')], max_length=20)),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.claim')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.subscription')),
            ],
            options={
                'db_table': 'documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='claim',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='core.subscription'),
        ),
    ]
